from __future__ import annotations

from sts2_sim.data import EnemyDef, EnemyMove


ENEMY_LIBRARY: dict[str, EnemyDef] = {
    # Prototype enemies kept for quick smoke tests.
    "twig_slime_s": EnemyDef(
        id="twig_slime_s",
        name="Small Twig Slime",
        min_hp=7,
        max_hp=11,
        ai="repeat",
        moves=(EnemyMove(id="tackle", intent="attack 4", damage=4),),
    ),
    "leaf_slime_s": EnemyDef(
        id="leaf_slime_s",
        name="Small Leaf Slime",
        min_hp=11,
        max_hp=15,
        ai="random_no_repeat",
        moves=(
            EnemyMove(id="tackle", intent="attack 3", damage=3),
            EnemyMove(id="goop", intent="add 1 Slimed", add_card_id="slimed", add_card_count=1),
        ),
    ),
    "twig_slime_m": EnemyDef(
        id="twig_slime_m",
        name="Medium Twig Slime",
        min_hp=26,
        max_hp=28,
        ai="weighted_random",
        moves=(
            EnemyMove(id="clump", intent="attack 11", damage=11),
            EnemyMove(id="sticky", intent="add 1 Slimed", add_card_id="slimed", add_card_count=1),
        ),
    ),
    # Underdocks weak / normal monsters.
    "corpse_slug_whip": EnemyDef(
        id="corpse_slug_whip",
        name="Corpse Slug",
        min_hp=25,
        max_hp=27,
        ai="cycle",
        moves=(
            EnemyMove(id="whip_slap", intent="attack 3x2", damage=3, hits=2),
            EnemyMove(id="glomp", intent="attack 8", damage=8),
            EnemyMove(id="goop", intent="frail 2", apply_player_power="frail", apply_player_power_amount=2),
        ),
        initial_powers=(("ravenous", 4),),
    ),
    "corpse_slug_glomp": EnemyDef(
        id="corpse_slug_glomp",
        name="Corpse Slug",
        min_hp=25,
        max_hp=27,
        ai="cycle",
        moves=(
            EnemyMove(id="glomp", intent="attack 8", damage=8),
            EnemyMove(id="goop", intent="frail 2", apply_player_power="frail", apply_player_power_amount=2),
            EnemyMove(id="whip_slap", intent="attack 3x2", damage=3, hits=2),
        ),
        initial_powers=(("ravenous", 4),),
    ),
    "corpse_slug_goop": EnemyDef(
        id="corpse_slug_goop",
        name="Corpse Slug",
        min_hp=25,
        max_hp=27,
        ai="cycle",
        moves=(
            EnemyMove(id="goop", intent="frail 2", apply_player_power="frail", apply_player_power_amount=2),
            EnemyMove(id="whip_slap", intent="attack 3x2", damage=3, hits=2),
            EnemyMove(id="glomp", intent="attack 8", damage=8),
        ),
        initial_powers=(("ravenous", 4),),
    ),
    "calcified_cultist": EnemyDef(
        id="calcified_cultist",
        name="Calcified Cultist",
        min_hp=38,
        max_hp=41,
        ai="cultist",
        moves=(
            EnemyMove(id="incantation", intent="gain Ritual 2", apply_power="ritual", apply_power_amount=2),
            EnemyMove(id="dark_strike", intent="attack 9", damage=9),
        ),
    ),
    "calcified_cultist_a10": EnemyDef(
        id="calcified_cultist_a10",
        name="Calcified Cultist",
        min_hp=39,
        max_hp=42,
        ai="cultist",
        moves=(
            EnemyMove(id="incantation", intent="gain Ritual 2", apply_power="ritual", apply_power_amount=2),
            EnemyMove(id="dark_strike", intent="attack 11", damage=11),
        ),
    ),
    "damp_cultist": EnemyDef(
        id="damp_cultist",
        name="Damp Cultist",
        min_hp=51,
        max_hp=53,
        ai="cultist",
        moves=(
            EnemyMove(id="incantation", intent="gain Ritual 5", apply_power="ritual", apply_power_amount=5),
            EnemyMove(id="dark_strike", intent="attack 1", damage=1),
        ),
    ),
    "fossil_stalker": EnemyDef(
        id="fossil_stalker",
        name="Fossil Stalker",
        min_hp=51,
        max_hp=53,
        ai="random_any",
        moves=(
            EnemyMove(id="latch", intent="attack 12", damage=12),
            EnemyMove(id="tackle", intent="attack 9 + frail 1", damage=9, apply_player_power="frail", apply_player_power_amount=1),
            EnemyMove(id="lash", intent="attack 3x2", damage=3, hits=2),
        ),
        initial_powers=(("suck", 3),),
    ),
    "gremlin_merc": EnemyDef(
        id="gremlin_merc",
        name="Gremlin Merc",
        min_hp=47,
        max_hp=49,
        ai="cycle",
        moves=(
            EnemyMove(id="gimme", intent="attack 7x2", damage=7, hits=2),
            EnemyMove(id="double_smash", intent="attack 6x2 + weak 2", damage=6, hits=2, apply_player_power="weak", apply_player_power_amount=2),
            EnemyMove(
                id="hehe",
                intent="attack 8 + strength 2",
                damage=8,
                apply_power="strength",
                apply_power_amount=2,
                apply_power_after_damage=True,
            ),
        ),
        initial_powers=(("surprise", 1), ("thievery", 20)),
    ),
    "fat_gremlin": EnemyDef(
        id="fat_gremlin",
        name="Fat Gremlin",
        min_hp=13,
        max_hp=17,
        ai="sequence",
        moves=(
            EnemyMove(id="spawned", intent="stunned"),
            EnemyMove(id="flee", intent="escape", escape=True),
        ),
    ),
    "sneaky_gremlin": EnemyDef(
        id="sneaky_gremlin",
        name="Sneaky Gremlin",
        min_hp=10,
        max_hp=14,
        ai="sequence",
        moves=(
            EnemyMove(id="spawned", intent="stunned"),
            EnemyMove(id="tackle", intent="attack 9", damage=9),
        ),
    ),
    "haunted_ship": EnemyDef(
        id="haunted_ship",
        name="Haunted Ship",
        min_hp=63,
        max_hp=63,
        ai="haunted_ship",
        moves=(
            EnemyMove(id="haunt", intent="weak 3 + add 5 Dazed", apply_player_power="weak", apply_player_power_amount=3, add_card_id="dazed", add_card_count=5),
            EnemyMove(id="swipe", intent="attack 13", damage=13),
            EnemyMove(id="stomp", intent="attack 4x3", damage=4, hits=3),
        ),
    ),
    "living_fog": EnemyDef(
        id="living_fog",
        name="Living Fog",
        min_hp=80,
        max_hp=80,
        ai="living_fog",
        moves=(
            EnemyMove(id="advanced_gas", intent="attack 8 + Smoggy", damage=8, apply_player_power="smoggy", apply_player_power_amount=1),
            EnemyMove(id="bloat", intent="attack 5 + summon Gas Bomb", damage=5, summon=("gas_bomb",)),
            EnemyMove(id="super_gas_blast", intent="attack 8", damage=8),
        ),
    ),
    "gas_bomb": EnemyDef(
        id="gas_bomb",
        name="Gas Bomb",
        min_hp=7,
        max_hp=7,
        ai="repeat",
        moves=(EnemyMove(id="explode", intent="attack 8 + die", damage=8, self_kill=True),),
        initial_powers=(("minion", 1),),
    ),
    "punch_construct": EnemyDef(
        id="punch_construct",
        name="Punch Construct",
        min_hp=55,
        max_hp=55,
        ai="cycle",
        moves=(
            EnemyMove(id="ready", intent="block 10", block=10),
            EnemyMove(id="fast_punch", intent="attack 5x2 + frail 1", damage=5, hits=2, apply_player_power="frail", apply_player_power_amount=1),
            EnemyMove(id="strong_punch", intent="attack 14", damage=14),
        ),
        initial_powers=(("artifact", 1),),
    ),
    "seapunk": EnemyDef(
        id="seapunk",
        name="Seapunk",
        min_hp=44,
        max_hp=46,
        ai="cycle",
        moves=(
            EnemyMove(id="sea_kick", intent="attack 11", damage=11),
            EnemyMove(id="spinning_kick", intent="attack 2x4", damage=2, hits=4),
            EnemyMove(id="bubble", intent="block 7 + strength 1", block=7, apply_power="strength", apply_power_amount=1),
        ),
    ),
    "sewer_clam": EnemyDef(
        id="sewer_clam",
        name="Sewer Clam",
        min_hp=56,
        max_hp=56,
        ai="cycle",
        moves=(
            EnemyMove(id="jet", intent="attack 10", damage=10),
            EnemyMove(id="pressurize", intent="strength 4", apply_power="strength", apply_power_amount=4),
        ),
        initial_powers=(("plating", 8),),
    ),
    "sludge_spinner": EnemyDef(
        id="sludge_spinner",
        name="Sludge Spinner",
        min_hp=37,
        max_hp=39,
        ai="random_no_repeat",
        moves=(
            EnemyMove(id="oil_spray", intent="attack 8 + weak 1", damage=8, apply_player_power="weak", apply_player_power_amount=1),
            EnemyMove(id="slam", intent="attack 11", damage=11),
            EnemyMove(
                id="rage",
                intent="attack 6 + strength 3",
                damage=6,
                apply_power="strength",
                apply_power_amount=3,
                apply_power_after_damage=True,
            ),
        ),
    ),
    "toadpole_front": EnemyDef(
        id="toadpole_front",
        name="Toadpole",
        min_hp=21,
        max_hp=25,
        ai="cycle",
        moves=(
            EnemyMove(id="spiken", intent="gain Thorns 2", apply_power="thorns", apply_power_amount=2),
            EnemyMove(id="spike_spit", intent="lose Thorns 2 + attack 3x3", damage=3, hits=3, apply_power="thorns", apply_power_amount=-2),
            EnemyMove(id="whirl", intent="attack 7", damage=7),
        ),
    ),
    "toadpole_back": EnemyDef(
        id="toadpole_back",
        name="Toadpole",
        min_hp=21,
        max_hp=25,
        ai="cycle",
        moves=(
            EnemyMove(id="whirl", intent="attack 7", damage=7),
            EnemyMove(id="spiken", intent="gain Thorns 2", apply_power="thorns", apply_power_amount=2),
            EnemyMove(id="spike_spit", intent="lose Thorns 2 + attack 3x3", damage=3, hits=3, apply_power="thorns", apply_power_amount=-2),
        ),
    ),
    "two_tailed_rat_scratch": EnemyDef(
        id="two_tailed_rat_scratch",
        name="Two-Tailed Rat",
        min_hp=17,
        max_hp=21,
        ai="rat_backup",
        moves=(
            EnemyMove(id="scratch", intent="attack 8", damage=8),
            EnemyMove(id="disease_bite", intent="attack 6", damage=6),
            EnemyMove(id="screech", intent="frail 1", apply_player_power="frail", apply_player_power_amount=1),
            EnemyMove(id="call_for_backup", intent="summon Two-Tailed Rat", summon=("two_tailed_rat_scratch",)),
        ),
    ),
    "two_tailed_rat_bite": EnemyDef(
        id="two_tailed_rat_bite",
        name="Two-Tailed Rat",
        min_hp=17,
        max_hp=21,
        ai="rat_backup",
        moves=(
            EnemyMove(id="disease_bite", intent="attack 6", damage=6),
            EnemyMove(id="screech", intent="frail 1", apply_player_power="frail", apply_player_power_amount=1),
            EnemyMove(id="scratch", intent="attack 8", damage=8),
            EnemyMove(id="call_for_backup", intent="summon Two-Tailed Rat", summon=("two_tailed_rat_scratch",)),
        ),
    ),
    "two_tailed_rat_screech": EnemyDef(
        id="two_tailed_rat_screech",
        name="Two-Tailed Rat",
        min_hp=17,
        max_hp=21,
        ai="rat_backup",
        moves=(
            EnemyMove(id="screech", intent="frail 1", apply_player_power="frail", apply_player_power_amount=1),
            EnemyMove(id="scratch", intent="attack 8", damage=8),
            EnemyMove(id="disease_bite", intent="attack 6", damage=6),
            EnemyMove(id="call_for_backup", intent="summon Two-Tailed Rat", summon=("two_tailed_rat_scratch",)),
        ),
    ),
    # Underdocks elites.
    "phantasmal_gardener_flail": EnemyDef(
        id="phantasmal_gardener_flail",
        name="Phantasmal Gardener",
        min_hp=26,
        max_hp=31,
        ai="gardener",
        moves=(
            EnemyMove(id="flail", intent="attack 1x3", damage=1, hits=3),
            EnemyMove(id="enlarge", intent="strength 2", apply_power="strength", apply_power_amount=2),
            EnemyMove(id="bite", intent="attack 5", damage=5),
            EnemyMove(id="lash", intent="attack 7", damage=7),
        ),
        initial_powers=(("skittish", 6),),
    ),
    "phantasmal_gardener_bite": EnemyDef(
        id="phantasmal_gardener_bite",
        name="Phantasmal Gardener",
        min_hp=26,
        max_hp=31,
        ai="gardener",
        moves=(
            EnemyMove(id="bite", intent="attack 5", damage=5),
            EnemyMove(id="lash", intent="attack 7", damage=7),
            EnemyMove(id="flail", intent="attack 1x3", damage=1, hits=3),
            EnemyMove(id="enlarge", intent="strength 2", apply_power="strength", apply_power_amount=2),
        ),
        initial_powers=(("skittish", 6),),
    ),
    "phantasmal_gardener_lash": EnemyDef(
        id="phantasmal_gardener_lash",
        name="Phantasmal Gardener",
        min_hp=26,
        max_hp=31,
        ai="gardener",
        moves=(
            EnemyMove(id="lash", intent="attack 7", damage=7),
            EnemyMove(id="flail", intent="attack 1x3", damage=1, hits=3),
            EnemyMove(id="enlarge", intent="strength 2", apply_power="strength", apply_power_amount=2),
            EnemyMove(id="bite", intent="attack 5", damage=5),
        ),
        initial_powers=(("skittish", 6),),
    ),
    "phantasmal_gardener_enlarge": EnemyDef(
        id="phantasmal_gardener_enlarge",
        name="Phantasmal Gardener",
        min_hp=26,
        max_hp=31,
        ai="gardener",
        moves=(
            EnemyMove(id="enlarge", intent="strength 2", apply_power="strength", apply_power_amount=2),
            EnemyMove(id="bite", intent="attack 5", damage=5),
            EnemyMove(id="lash", intent="attack 7", damage=7),
            EnemyMove(id="flail", intent="attack 1x3", damage=1, hits=3),
        ),
        initial_powers=(("skittish", 6),),
    ),
    "skulking_colony": EnemyDef(
        id="skulking_colony",
        name="Skulking Colony",
        min_hp=75,
        max_hp=75,
        ai="skulking_colony",
        moves=(
            EnemyMove(id="zoom", intent="attack 14", damage=14),
            EnemyMove(id="zoom", intent="attack 14", damage=14),
            EnemyMove(
                id="inertia",
                intent="attack 9 + strength 2",
                damage=9,
                apply_power="strength",
                apply_power_amount=2,
                apply_power_after_damage=True,
            ),
            EnemyMove(id="piercing_stabs", intent="attack 7x2", damage=7, hits=2),
        ),
        initial_powers=(("hardened_shell", 20),),
    ),
    "terror_eel": EnemyDef(
        id="terror_eel",
        name="Terror Eel",
        min_hp=140,
        max_hp=140,
        ai="terror_eel",
        moves=(
            EnemyMove(id="crash", intent="attack 16", damage=16),
            EnemyMove(
                id="thrash",
                intent="attack 3x3 + Vigor 6",
                damage=3,
                hits=3,
                apply_power="vigor",
                apply_power_amount=6,
                apply_power_after_damage=True,
            ),
            EnemyMove(id="stun", intent="stunned"),
            EnemyMove(id="terror", intent="vulnerable 99", apply_player_power="vulnerable", apply_player_power_amount=99),
        ),
        initial_powers=(("shriek", 70),),
    ),
    "terror_eel_a9": EnemyDef(
        id="terror_eel_a9",
        name="Terror Eel",
        min_hp=150,
        max_hp=150,
        ai="terror_eel",
        moves=(
            EnemyMove(id="crash", intent="attack 18", damage=18),
            EnemyMove(
                id="thrash",
                intent="attack 4x3 + Vigor 6",
                damage=4,
                hits=3,
                apply_power="vigor",
                apply_power_amount=6,
                apply_power_after_damage=True,
            ),
            EnemyMove(id="stun", intent="stunned"),
            EnemyMove(id="terror", intent="vulnerable 99", apply_player_power="vulnerable", apply_player_power_amount=99),
        ),
        initial_powers=(("shriek", 75),),
    ),
    # Underdocks bosses.
    "lagavulin_matriarch": EnemyDef(
        id="lagavulin_matriarch",
        name="Lagavulin Matriarch",
        min_hp=222,
        max_hp=222,
        ai="lagavulin_matriarch",
        moves=(
            EnemyMove(id="sleep", intent="asleep"),
            EnemyMove(id="slash", intent="attack 19", damage=19),
            EnemyMove(id="disembowel", intent="attack 9x2", damage=9, hits=2),
            EnemyMove(id="slash2", intent="attack 12 + block 12", damage=12, block=12),
            EnemyMove(
                id="soul_siphon",
                intent="-2 Str/Dex + gain 2 Str",
                apply_player_power="strength",
                apply_player_power_amount=-2,
                extra_player_powers=(("dexterity", -2),),
                apply_power="strength",
                apply_power_amount=2,
            ),
        ),
        initial_powers=(("plating", 12), ("asleep", 3)),
    ),
    "soul_fysh": EnemyDef(
        id="soul_fysh",
        name="Soul Fysh",
        min_hp=211,
        max_hp=211,
        ai="soul_fysh",
        moves=(
            EnemyMove(id="beckon", intent="add 2 Beckon"),
            EnemyMove(id="de_gas", intent="attack 16", damage=16),
            EnemyMove(id="gaze", intent="attack 7 + add 1 Beckon", damage=7),
            EnemyMove(id="fade", intent="intangible 2", apply_power="intangible", apply_power_amount=2),
            EnemyMove(id="scream", intent="attack 13 + vulnerable 3", damage=13, apply_player_power="vulnerable", apply_player_power_amount=3),
        ),
    ),
    "waterfall_giant": EnemyDef(
        id="waterfall_giant",
        name="Waterfall Giant",
        min_hp=240,
        max_hp=240,
        ai="waterfall_giant",
        moves=(
            EnemyMove(id="pressurize", intent="Steam Eruption 15", apply_power="steam_eruption", apply_power_amount=15),
            EnemyMove(
                id="stomp",
                intent="attack 15 + weak 1 + pressure",
                damage=15,
                apply_player_power="weak",
                apply_player_power_amount=1,
                apply_power="steam_eruption",
                apply_power_amount=3,
                apply_power_after_damage=True,
            ),
            EnemyMove(
                id="ram",
                intent="attack 10 + pressure",
                damage=10,
                apply_power="steam_eruption",
                apply_power_amount=3,
                apply_power_after_damage=True,
            ),
            EnemyMove(id="siphon", intent="heal 10 + pressure", heal=10, apply_power="steam_eruption", apply_power_amount=3),
            EnemyMove(
                id="pressure_gun",
                intent="attack 20 + pressure",
                damage=20,
                apply_power="steam_eruption",
                apply_power_amount=3,
                apply_power_after_damage=True,
            ),
            EnemyMove(
                id="pressure_up",
                intent="attack 13 + pressure",
                damage=13,
                apply_power="steam_eruption",
                apply_power_amount=3,
                apply_power_after_damage=True,
            ),
            EnemyMove(id="about_to_blow", intent="stunned"),
            EnemyMove(id="explode", intent="attack Steam Eruption + die", self_kill=True),
        ),
    ),
}


UNDERDOCKS_WEAK_ENCOUNTERS: dict[str, list[str]] = {
    "corpse_slugs_weak": ["corpse_slug_whip", "corpse_slug_glomp"],
    "seapunk_weak": ["seapunk"],
    "sludge_spinner_weak": ["sludge_spinner"],
    "toadpoles_weak": ["toadpole_front", "toadpole_back"],
}


UNDERDOCKS_REGULAR_ENCOUNTERS: dict[str, list[str]] = {
    "corpse_slugs_normal": ["corpse_slug_whip", "corpse_slug_glomp", "corpse_slug_goop"],
    "cultists_normal": ["calcified_cultist", "damp_cultist"],
    "fossil_stalker_normal": ["fossil_stalker"],
    "gremlin_merc_normal": ["gremlin_merc"],
    "haunted_ship_normal": ["haunted_ship"],
    "living_fog_normal": ["living_fog"],
    "punch_construct_normal": ["punch_construct"],
    "seapunk_normal": ["calcified_cultist", "seapunk"],
    "sewer_clam_normal": ["sewer_clam"],
    "two_tailed_rats_normal": ["two_tailed_rat_scratch", "two_tailed_rat_bite", "two_tailed_rat_screech"],
}


UNDERDOCKS_ELITE_ENCOUNTERS: dict[str, list[str]] = {
    "phantasmal_gardeners_elite": [
        "phantasmal_gardener_flail",
        "phantasmal_gardener_bite",
        "phantasmal_gardener_lash",
        "phantasmal_gardener_enlarge",
    ],
    "skulking_colony_elite": ["skulking_colony"],
    "terror_eel_elite": ["terror_eel"],
}


UNDERDOCKS_BOSS_ENCOUNTERS: dict[str, list[str]] = {
    "lagavulin_matriarch_boss": ["lagavulin_matriarch"],
    "soul_fysh_boss": ["soul_fysh"],
    "waterfall_giant_boss": ["waterfall_giant"],
}


ENCOUNTERS: dict[str, list[str]] = {
    "single_small_slime": ["twig_slime_s"],
    "two_small_slimes": ["leaf_slime_s", "twig_slime_s"],
    "medium_slime": ["twig_slime_m"],
    "cultist": ["calcified_cultist"],
    **UNDERDOCKS_WEAK_ENCOUNTERS,
    **UNDERDOCKS_REGULAR_ENCOUNTERS,
    **UNDERDOCKS_ELITE_ENCOUNTERS,
    **UNDERDOCKS_BOSS_ENCOUNTERS,
    "terror_eel_a9_elite": ["terror_eel_a9"],
}
